require 'erb'
require 'monopoly/board'
require 'monopoly/card'
require 'monopoly/jail_card'
require 'monopoly/free_parking'
require 'monopoly/vcard'
require 'monopoly/hcard'
require 'monopoly/card_row'